site_name: Site-Doc for Nix Config

site_url: https://neop26.github.io/nixpublic/
theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Deployment: deployment.md

copyright: |
  &copy; 2023 <a href="https://github.com/neop26"  target="_blank" rel="noopener">Aben Samuel</a>